### ISSUE TITLE
관리자 페이지의 애니메이션 편성표, 2024 편성표에서 X(트위터) 아이콘 미표시 버그

### ISSUE THREAD

**Issue by CodeName393** [anissia-net/web#21]
관리자 페이지의 애니메이션 편성표와 2024 편성표에서 X(트위터) 아이콘이 표시되지 않습니다.
다만, 같은 코드를 사용하는 기본 애니메이션 목록 페이지에서는 X(트위터)아이콘이 정상 표시됩니다.

**Comment by marker-seoul** [comment]
버그는 아니고 원래 없던 기능인데요.
일단 백엔드는 추가해놨습니다.

https://github.com/anissia-net/anissia-core/commit/2ae6753685dc26aa5905d98e6088ffdda0c5cce3
